### PR TITLE
Remove "," from tuple definition of remote method

### PR DESCRIPTION
**Pull request by cspinillo**
…draw.

Will cause unnecessary token error

#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by cspinillo** [comment]
What format would you like the commit message in? I'd like to fix it, but I'm unsure of what to fix it to, or how to fix (amend/new/etc.)

**Comment by cspinillo** [comment]
Updated comment based on output from Linter

**Comment by b-admike** [comment]
@cspinillo Sorry for the late reply, but the issue was still your commit message title was more than 50 characters long. Therefore, I have re-phrased it to `Fix donate and withdraw definitions` and left your complete description in your commit message body. Here are the steps I took to do that for your reference:
```
___________________    | ~/loopback/community/cspinillo/loopback-example-access-control @ biniams-mbp (badmike)
| => git remote add upstream git@github.com:strongloop/loopback-example-access-control.git
___________________    | ~/loopback/community/cspinillo/loopback-example-access-control @ biniams-mbp (badmike)
| => git remote -v
origin  git@github.com:cspinillo/loopback-example-access-control.git (fetch)
origin  git@github.com:cspinillo/loopback-example-access-control.git (push)
upstream        git@github.com:strongloop/loopback-example-access-control.git (fetch)
upstream        git@github.com:strongloop/loopback-example-access-control.git (push)
___________________    | ~/loopback/community/cspinillo/loopback-example-access-control @ biniams-mbp (badmike)
| => git checkout patch-1
Branch patch-1 set up to track remote branch patch-1 from origin.
Switched to a new branch 'patch-1'
___________________    | ~/loopback/community/cspinillo/loopback-example-access-control @ biniams-mbp (badmike)
| => git rebase -i upstream/master
[detached HEAD 34f46f8] Fix donate and withdraw definitions
 Author: Christian Spinillo <christian.spinillo@gmail.com>
 Date: Tue Dec 26 14:06:39 2017 -0500
 1 file changed, 2 insertions(+), 2 deletions(-)
Successfully rebased and updated refs/heads/patch-1.
___________________    | ~/loopback/community/cspinillo/loopback-example-access-control @ biniams-mbp (badmike)
| => git push origin +patch-1
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (5/5), 528 bytes | 0 bytes/s, done.
Total 5 (delta 3), reused 3 (delta 2)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To git@github.com:cspinillo/loopback-example-access-control.git
 + a3e67f4...34f46f8 patch-1 -> patch-1 (forced update)
```

The main command here is the `git rebase -i upstream/master` which is an interactive rebase and puts your commit on top of all the commits from `upstream/master`. I put `r` instead of `pick` for your commit which is to reword it, then modified the commit title (which is first) and the commit message body to adhere to our lint rules. Thank you for your contribution, we can land your patch now!

**Pull request merged**
