### PR TITLE
Correct grammar

### PR DESCRIPTION
**Pull request by manishbalodia**
At Line no-> 250 
"Administator" to "Administrator"

#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@manishbalodia , thanks for fixing the typo.  Could you please amend the commit message to reflect that (`grammer` should be `grammar` btw)? thanks!

**Comment by dhmlau** [comment]
Hi @manishbalodia , thanks for fixing the description.  Actually what i meant was fixing the commit message.  It can be done through `git commit --amend` command.  https://help.github.com/en/articles/changing-a-commit-message

Thanks!

**Comment by dhmlau** [comment]
@manishbalodia , I've rebased and fixed the commit linter error for you.  Your PR has bee merged! 🎉

**Pull request merged**
