### PR TITLE
Changed app.models.User to app.models.User

### PR DESCRIPTION
**Pull request by kexoth**
There's a typo in the example.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
Hi @kexoth, thank you for the pull request. The `user` model name is intentional, see https://github.com/strongloop/loopback-example-access-control/blob/ca9c9c23aaa77031aa2396aa343e2df751912878/common/models/user.json.

**Comment by kexoth** [comment]
@bajtos didn't knew that part, the sample code wasn't working for me unless I changed that. 
Thanks for reaching out on this.

**Comment by bajtos** [comment]
> the sample code wasn't working for me unless I changed that. 

Could you please open a new issue here in this repository and provide more details on what does it mean "wasn't working"? We need information that will allow us to reproduce the problem locally on our machines.

**Pull request closed without merging**
